
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /static/h2-console

  devtools:
    restart:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.example.demo.ts.vo
  mapper-locations: mapper/*.xml

logging:
  level:
    root: debug
    org:
      springframework:
        boot:
          autoconfigure: ERROR
    com:
      zaxxer:
        hikari: ERROR

server:
  servlet:
    session:
      timeout: 10m

cloud:
  aws:
    s3:
      bucket: dev-attach-file-bucket
    endpoint:
      static: https://kr.object.gov-ncloudstorage.com
    region:
      static: gov-standard
    credentials:
      access-key: 601D8D4DEE4344D8AE04
      secret-key: B5BEE68094CE7B179A03B0763E9CA464D55922D3
