apiVersion: v1
kind: Pod
metadata:
  labels:
    agent: jenkins-agent-develop
spec:
  securityContext:
    runAsUser: 0
  imagePullSecrets:
    - name: regcrd
  serviceAccountName: jenkins-admin
  restartPolicy: Never
  hostAliases:
    - ip: 172.21.2.83
      hostnames:
        - uap-gitlab.bizplay.co.kr
    - ip: 172.21.4.20
      hostnames:
        - private-d0de783e-kr2-registry.container.gov-nhncloud.com
    - ip: 172.21.4.5
      hostnames:
        - kr2-api-object-storage.gov-nhncloudservice.com
  containers:
    - name: maven
      image: maven:3.8.2-openjdk-11-slim
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - 99m
      resources:
        requests:
          memory: 1Gi
          cpu: 200m
      volumeMounts:
        - name: volume-mvn
          mountPath: /root/.m2/repository
    - name: kaniko-warmer
      image: private-d0de783e-kr2-registry.container.gov-nhncloud.com/dev-k8s-registry/custom-kaniko-warmer:1.0
      command:
        - sleep
      args:
        - 99m
      volumeMounts:
        - name: jenkins-pcr
          mountPath: /kaniko/.docker
        - name: volume-kaniko
          mountPath: /cache
    - name: kaniko-c0
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - 99m
      volumeMounts:
        - name: jenkins-pcr
          mountPath: /kaniko/.docker
        - name: volume-kaniko
          mountPath: /cache
    - name: kaniko-c1
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - 99m
      volumeMounts:
        - name: jenkins-pcr
          mountPath: /kaniko/.docker
        - name: volume-kaniko
          mountPath: /cache
    - name: kaniko-c2
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - 99m
      volumeMounts:
        - name: jenkins-pcr
          mountPath: /kaniko/.docker
        - name: volume-kaniko
          mountPath: /cache
    - name: kubectl
      image: bitnami/kubectl:1.26.10
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - 99m
  volumes:
    - name: volume-mvn
      persistentVolumeClaim:
        claimName: maven-pv-claim
    - name: volume-kaniko
      persistentVolumeClaim:
        claimName: kaniko-pv-claim
    - name: jenkins-pcr
      projected:
        sources:
          - secret:
              name: regcrd
              items:
                - key: .dockerconfigjson
                  path: config.json
