apiVersion: v1
kind: Pod
metadata:
  labels:
    agent: jenkins-agent
spec:
  securityContext:
    runAsUser: 0
  imagePullSecrets:
    - name: dev-reg-secret
  serviceAccountName: jenkins-admin
  restartPolicy: Never
  containers:
    - name: maven
      image: maven:3.8.2-openjdk-11
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - 99m
      resources:
        limits:
          memory: 2Gi
          cpu: 500m
      volumeMounts:
        - name: volume-mvn
          mountPath: /root/.m2/repository
    - name: kaniko-c0
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - 99m
      volumeMounts:
        - name: jenkins-pcr
          mountPath: /kaniko/.docker
        - name: volume-kaniko
          mountPath: /cache
    - name: kaniko-c1
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - 99m
      volumeMounts:
        - name: jenkins-pcr
          mountPath: /kaniko/.docker
        - name: volume-kaniko
          mountPath: /cache
    - name: kaniko-c2
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - 99m
      volumeMounts:
        - name: jenkins-pcr
          mountPath: /kaniko/.docker
        - name: volume-kaniko
          mountPath: /cache
    - name: kubectl
      image: bitnami/kubectl:1.29.0
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - 99m
    - name: kaniko-warmer
      image: pqf1vv9m.private-ncr.gov-ntruss.com/custom-kaniko-warmer:1.0
      command:
        - sleep
      args:
        - 99m
      volumeMounts:
        - name: jenkins-pcr
          mountPath: /kaniko/.docker
        - name: volume-kaniko
          mountPath: /cache
  volumes:
    - name: volume-mvn
      persistentVolumeClaim:
        claimName: maven-pv-claim
    - name: volume-kaniko
      persistentVolumeClaim:
        claimName: kaniko-pv-claim
    - name: jenkins-pcr
      projected:
        sources:
          - secret:
              name: dev-reg-secret
              items:
                - key: .dockerconfigjson
                  path: config.json